### ISSUE TITLE
Flashing info incorrect

### ISSUE THREAD

**Issue by pwebb-home** [0xCB-dev/0xCB-Helios#3]
Issuing a "make 0xcb/helios:default:flash"  in the qmk repo after cloning gets a:

`QMK Firmware 0.22.14
make: *** No rule to make target '0xcb/helios:default:flash'. Stop.
|
| QMK's make format is:
|     make keyboard_folder:keymap_folder[:target]
|
| Where `keyboard_folder` is the path to the keyboard relative to
| `qmk_firmware/keyboards/`, and `keymap_folder` is the name of the
| keymap folder under that board's `keymaps/` directory.
|
| Examples:
|     keyboards/dz60, keyboards/dz60/keymaps/default
|       -> make dz60:default
|       -> qmk compile -kb dz60 -km default
|     keyboards/planck/rev6, keyboards/planck/keymaps/default
|       -> make planck/rev6:default:flash
|       -> qmk flash -kb planck/rev6 -km default`

**Comment by Conor-Burns** [comment]
That's because it's just the test firmware used to verify functionality of all pins.

This command is an example for QMK - replace Helios with the name of the keyboard you'd like to use.
