### ISSUE TITLE
Info about bootloader access when reset button is inaccessible 

### ISSUE THREAD

**Issue by tonykakuuu** [0xCB-dev/0xCB-Helios#4]
Some boards require you to solder the board upside down, making the reset button inaccessible. For these boards, the user needs to short RST and GND to access the bootloader. Please include this info at least somewhere on the README page. I know you can deduce it from the pinout but I'm pretty sure users who don't know much about circuitry are going to end up wondering about alternative ways of flashing their Helios.

**Comment by Conor-Burns** [comment]
Thanks for the info - I'll add it to the readme.
