### ISSUE TITLE
Board won't enter bootloader mode

### ISSUE THREAD

**Issue by ethangamma24** [0xCB-dev/0xCB-Helios#5]
Hi there! I just got two of these boards as part of a corner keyboard kit. I've been attempting to flash firmware to them, but the boards won't enter bootloader mode. When I plug them into my computer (M1 MacBook Pro) I see the device listed as "RPI-RP2" with two files inside: INDEX.HTM and INFO_UF2.TXT. When I press and hold the reset button for the >500ms specified, the device briefly disappears, then reappears in the exact same manner. I have attempted to enter bootloader mode by shorting the RST and GND pins that are next to each other, and still nothing. I've tried both boards with the same results. I've done lots of googling, but am unable to find anyone else with these issues. Any ideas as to what the problem might be and how it can be solved? Thanks!

**Comment by Conor-Burns** [comment]
Did you buy the board through any of the vendors listed in here: https://docs.keeb.supply/0xcb-helios/infos/

**Comment by ethangamma24** [comment]
I did not, it was purchased through https://keebd.com/en-us.

**Comment by Conor-Burns** [comment]
Yeah sorry. We are getting a lot of support requests from customers from keebd. Since we are not supplying keebd with the helioses and they seem to have a lot of quality issues we stopped giving customer support to helioses not bought through official vendors. I hope that you can understand that.

Best of luck!

**Comment by ethangamma24** [comment]
Totally understood, thank you so much for the reply!! I'll try and get a refund ASD purchase the boards through one of your vendors.

**Comment by medoix** [comment]
@ethangamma24 have you opened and read the INDEX.HTM and INFO_UF2.TXT files you mentioned? When you see these files, the Helios is in bootloader mode and ready to accept the .uf2 firmware file. This is not a quality issue.

**Comment by ethangamma24** [comment]
I have indeed opened and read them, but the files are locked and I'm unable to move any files into the drive. When I attempt to flash with QMK, the program errors out stating that the drive is in read only mode.

**Comment by medoix** [comment]
Could this be computer related? Could you test one on a different PC. When the Helios brings up the File Explorer that indicates that it is in bootloader mode and ready for the firmware as you noted. Once you drag the uf2 firmware onto it the File Explorer will stop popping up on connection and will instead run the firmware in keyboard mode.

**Comment by ethangamma24** [comment]
Actually now that I think about it, it could be the computer not allowing it to open in anything other than read only (there are some administrative restrictions on the machine). I'll try later this evening on another device.
