### ISSUE TITLE
Does it work with QMK?

### ISSUE THREAD

**Issue by ironlungx** [0xCB-dev/0xCB-Helios#6]
I'm building a corne keyboard with the Helios Controller (haven't bought it yet). Can use QMK for programming it?

**Comment by Conor-Burns** [comment]
Hi, yes you can program it with qmk (https://github.com/0xCB-dev/0xCB-Helios?tab=readme-ov-file#flashing) please read the readme before opening an issue.
Follow qmk docs on how to generate files for a rp2040ce microcontroller.
